db:
  image: mysql:latest
  environment:
    - MYSQL_ROOT_PASSWORD=root
web:
  build: .
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  volumes:
    - .:/myapp
    - ./tools/mysql:/etc/mysql/conf.d
  ports:
    - "3000:3000"
  links:
    - db
